### ISSUE TITLE
Save All button & colored active tab

### ISSUE THREAD

**Issue by AdmiralRazorbeard** [McSodbrenner/vscode-better-open-editors#19]
First of all, thank you for this. I love what you're trying to achieve, this is more handy and clear than the actual tabs. I place that window to the left of the terminal which make it more handy to use imho.

I have two questions:
- Can we have a "save all" button which could be placed where the "refresh" and the "settings" button currently are ?
- I use the "tab.activeBackground" option to change the current tab background color. Is there a way to achieve something similar in the Better Open Editors window ?

**Comment by McSodbrenner** [comment]
For myself. More info here:
https://stackoverflow.com/a/74493474

**Comment by McSodbrenner** [comment]
@AdmiralRazorbeard
The implementation of the "Save all" button was no problem and will go out with the next release.

But I can only change the foreground color of the items and not their background color. This can only be done globally via the theming. In this case, that would be "list.activeSelectionBackground", which you can set in your "workbench.colorCustomizations". However, this then affects all active selections in lists.
