### ISSUE TITLE
Error state: "There is no data provider registered that can provide view data."

### ISSUE THREAD

**Issue by sboagy** [McSodbrenner/vscode-better-open-editors#27]
All of the sudden, Better Open Editors panel just reports "There is no data provider registered that can provide view data.".

Extension version: `v1.11.2`

The extension was working fine, for about 3 weeks.

If I click on the little disks icon, it reports "Error running command betterOpenEditors.saveAll: command 'betterOpenEditors.saveAll' not found. This is likely caused by the extension that contributes betterOpenEditors.saveAll."

If I click on output->extension host, I get:

> 2024-08-26 15:41:55.517 [error] Error: [ExtensionListenerError] Extension 'McSodbrenner.better-open-editors' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'replace')
>     at i.value (/Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:21030)
>     at n.B (/Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:737)
>     at n.C (/Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:807)
>     at n.fire (/Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:1023)
>     at n.$acceptConfigurationChanged (/Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:48999)
>     at /Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:48543
> 

My only thought is that I might have inadvertently deleted some needed file or something?

In my user extensions I have:
```JSON
{
    "betterOpenEditors.PackagePatterns": "**/components\n**/components/ui\n**/components/*\n**/modules/*\n**/app\n**/auth",
    "betterOpenEditors.ShowPackageIcon": true
}
```

I uninstalled and re-installed Better Open Editors extension, to no avail.

VSCode version:

> Version: 1.92.2
> Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
> Date: 2024-08-14T17:29:30.058Z
> Electron: 30.1.2
> ElectronBuildId: 9870757
> Chromium: 124.0.6367.243
> Node.js: 20.14.0
> V8: 12.4.254.20-electron.0
> OS: Darwin arm64 23.6.0

**Comment by sboagy** [comment]
Today the extension is working again.  For whatever reason.

**Comment by McSodbrenner** [comment]
Great to hear. Thanks for notifying.
