### ISSUE TITLE
Sort open files alphabetically

### ISSUE THREAD

**Issue by ChristopherHaws** [McSodbrenner/vscode-better-open-editors#28]
It would be great if there were an option to sort the files alphabetically within the folders. Right now they don't appear in any discernible order. Thanks for the great extension!

![image](https://github.com/user-attachments/assets/c9ab346a-daaf-4b1e-b1c8-f3184dc03f33)

**Comment by McSodbrenner** [comment]
@ChristopherHaws I have problems to reproduce it.
Could you please provide an example folder structure and the content of the "Package Patterns" field in your settings?

**Comment by McSodbrenner** [comment]
Could not reproduce it, sorry.
